Repository knoxite/website, pull requests merged in 2020-04, with the labels that each got.

#13 Added documentation for Azure File Storage backend
  content/docs/storage-backends/content.md
  layouts/shortcodes/note.html
  static/images/backends/azure_access_keys.png
  static/images/backends/azure_access_keys_focus.png
  static/images/backends/azure_create_file_storage.png
  static/images/backends/azure_create_file_storage_2.png
  static/images/backends/azure_create_file_storage_2_focus.png
  static/images/backends/azure_create_file_storage_focus.png
  static/images/backends/azure_create_folder_copy_url.png
  static/images/backends/azure_create_folder_copy_url_focus.png
Labels: documentation, enhancement

#15 Documentation on the backblaze b2 cloud storage backend
  content/docs/storage-backends/content.md
  static/images/backends/backblaze_add_application_key.png
  static/images/backends/backblaze_add_application_key_focus.png
  static/images/backends/backblaze_create_new_key.png
  static/images/backends/backblaze_create_new_key_focus.png
  static/images/backends/backblaze_key_created.png
  static/images/backends/backblaze_key_created_focus.png
Labels: documentation

#16 Updated dropbox images for storage backend documentation
  content/docs/storage-backends/content.md
  static/images/backends/dropbox_create_app.png
  static/images/backends/dropbox_create_new_app.png
  static/images/backends/dropbox_create_new_app_focus.png
  static/images/backends/dropbox_generate_access_token.png
  static/images/backends/dropbox_generate_access_token_focus.png
  static/images/backends/dropbox_generate_token.png
  static/images/backends/dropbox_generated_access_token.png
  static/images/backends/dropbox_generated_access_token_focus.png
  static/images/backends/dropbox_generated_token.png
Labels: documentation

#19 NextCloud Documentation
  content/docs/storage-backends/content.md
  static/images/backends/owncloud_nextcloud/nextcloud_apppassword_step1.png
  static/images/backends/owncloud_nextcloud/nextcloud_apppassword_step2.png
  static/images/backends/owncloud_nextcloud/nextcloud_webdav_path.png
Labels: documentation

#20 Added Google Cloud Storage documentation, re-organised images for sto…
  content/docs/storage-backends/content.md
  static/images/backends/azure/azure_access_keys.png
  static/images/backends/azure/azure_access_keys_focus.png
  static/images/backends/azure/azure_create_file_storage.png
  static/images/backends/azure/azure_create_file_storage_2.png
  static/images/backends/azure/azure_create_file_storage_2_focus.png
  static/images/backends/azure/azure_create_file_storage_focus.png
  static/images/backends/azure/azure_create_folder_copy_url.png
  static/images/backends/azure/azure_create_folder_copy_url_focus.png
  static/images/backends/backblaze/backblaze_add_application_key.png
  static/images/backends/backblaze/backblaze_add_application_key_focus.png
  static/images/backends/backblaze/backblaze_create_new_key.png
  static/images/backends/backblaze/backblaze_create_new_key_focus.png
  static/images/backends/backblaze/backblaze_key_created.png
  static/images/backends/backblaze/backblaze_key_created_focus.png
  static/images/backends/dropbox/dropbox_create_new_app.png
  static/images/backends/dropbox/dropbox_create_new_app_focus.png
  static/images/backends/dropbox/dropbox_generate_access_token.png
  static/images/backends/dropbox/dropbox_generate_access_token_focus.png
  static/images/backends/dropbox/dropbox_generated_access_token.png
  static/images/backends/dropbox/dropbox_generated_access_token_focus.png
  static/images/backends/googlecloud/focus/gcloud_create_bucket1_focus.png
  static/images/backends/googlecloud/focus/gcloud_create_bucket2_focus.png
  static/images/backends/googlecloud/focus/gcloud_create_folder_focus.png
  static/images/backends/googlecloud/focus/gcloud_create_project_focus.png
  static/images/backends/googlecloud/focus/gcloud_serviceaccount_create_focus.png
  static/images/backends/googlecloud/focus/gcloud_serviceaccount_createkey_focus.png
  static/images/backends/googlecloud/focus/gcloud_serviceaccount_finish_createkey_focus.png
  static/images/backends/googlecloud/focus/gcloud_serviceaccount_grantaccess_focus.png
  static/images/backends/googlecloud/gcloud_bucket_overview.png
  static/images/backends/googlecloud/gcloud_buckets.png
  static/images/backends/googlecloud/gcloud_create_bucket1.png
  static/images/backends/googlecloud/gcloud_create_bucket2.png
  static/images/backends/googlecloud/gcloud_create_folder.png
  static/images/backends/googlecloud/gcloud_create_folder_finished.png
  static/images/backends/googlecloud/gcloud_create_project.png
  static/images/backends/googlecloud/gcloud_create_project_finished.png
  static/images/backends/googlecloud/gcloud_projects.png
  static/images/backends/googlecloud/gcloud_serviceaccount_create.png
  static/images/backends/googlecloud/gcloud_serviceaccount_createkey.png
  static/images/backends/googlecloud/gcloud_serviceaccount_findinmenu.png
  static/images/backends/googlecloud/gcloud_serviceaccount_finish_createkey.png
  static/images/backends/googlecloud/gcloud_serviceaccount_grantaccess.png
  static/images/backends/googlecloud/gcloud_serviceaccount_key_created.png
  static/images/backends/googlecloud/gcloud_serviceaccount_key_download.png
  static/images/backends/googlecloud/gcloud_serviceaccounts.png
Labels: documentation

#14 Added Blog post for week15 of 2020
  content/blog/02-this-week-in-knoxite-week-15-2020/index.md
  static/images/2020/15/week15_webpage_landing_page.png
Labels: blog

#24 Removed sidebar at blogposts to fix alignment
  content/blog/01-we-are-knoxite/index.md
  content/blog/02-this-week-in-knoxite-week-15-2020/index.md
Labels: blog

#27 Updated Guide
  content/docs/guide/content.md
Labels: documentation

#29 Added information about snapshots in the guide section
  content/docs/guide/content.md
Labels: documentation

#30 Added URL-Encoded note
  content/docs/storage-backends/content.md
  layouts/shortcodes/note-urlencoded.html
Labels: documentation

#31 Mention further flags for snapshots in the guide section
  content/docs/guide/content.md
Labels: documentation
